export const menus = [
  {
    id: 1,
    name: "Dashboard",
    path: "/",
  },
  {
    id: 2,
    name: "Lowongan",
    path: "/lowongan",
  },
  {
    id: 3,
    name: "Pelamar",
    path: "/pelamar",
  },
  {
    id: 4,
    name: "Pelamar Cabang",
    path: "/pelamar-cabang",
  },
  {
    id: 5,
    name: "Jadwal Test",
    path: "/jadwal-test",
  },
];

export const dummyDashboard = [
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
  {
    id: 1,
    nama: "Munchaminna",
    email: "munchmunchaww@gmail.com",
    nomor_hp: "085123456789",
    lokasi: "Jakarta",
    pendidikan_terakhir: "S-1",
    skill: "UI/UX",
    posisi: "UI/UX",
    linkedin: "Munchaminna",
    kategori: "Potensial",
  },
];
